#page title
page_title                                : GoChimp                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.onetapstudios.GoChimpMemoryGame
app_icon                                  : assets/gochimplogo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : GoChimp                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : "GoChimp: The Impossible Memory Game"

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 1tapstudios                                
your_link                                 : https://1tapstudios.github.io                     
your_city                                 : Mumbai                                
email_address                             : 1tapstudio@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 1tapstudios
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#191919"
topbar_transparency                       : 0.1
topbar_title_color                        : "#7fff00"

cover_image                               : assets/game-grid.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#191919"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#191919"

link_color                                : "#7fff00"

app_title_color                           : "#7fff00"
app_price_color                           : "#7fff00"
app_description_color                     : "#7fff00"

feature_title_color                       : "#7fff00"
feature_text_color                        : "#7fff00"

feature_icons_foreground_color            : "#7fff00"
feature_icons_background_color            : "#191919"

social_icons_foreground_color             : "#7fff00"
social_icons_background_color             : "#191919"

footer_text_color                         : "#7fff00"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown